FROM centos
MAINTAINER zck
COPY mysql.sh /usr/local
COPY bootstrap.sh /etc/bootstrap.sh
RUN yum install -y initscripts net-tools passwd openssl openssh-server openssh-clients numactl libaio tar  perl perl-devel perl-Data-Dumper  \

    && ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' \
    && ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' \
    && ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key  -N ''  \
    && ssh-keygen -f /root/.ssh/id_rsa -N '' \
    && touch /root/.ssh/authorized_keys \
    && cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys \
    && sed -i "s/UsePAM.*/UsePAM no/g" /etc/ssh/sshd_config \
    && sed -i "s/#UsePrivilegeSeparation.*/UsePrivilegeSeparation no/g" /etc/ssh/sshd_config \
    && sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/g' /etc/ssh/ssh_config \
    && chmod 700 /usr/local/mysql.sh \
    && echo "root:123456" | chpasswd \
    && chown root.root /etc/bootstrap.sh \
    && chmod 700 /etc/bootstrap.sh \
    && mkdir /var/run/sshd

CMD ["/usr/sbin/init"]
ENTRYPOINT ["/etc/bootstrap.sh"]