FROM centos
MAINTAINER zck

RUN yum install -y passwd openssl openssh-server openssh-clients \
&& ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' \
&& ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' \
&& ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key  -N ''  \
&& ssh-keygen -f /root/.ssh/id_rsa -N '' \
&& touch /root/.ssh/authorized_keys \
&& cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys \
&& sed -i "s/UsePAM.*/UsePAM no/g" /etc/ssh/sshd_config \
&& sed -i "s/#UsePrivilegeSeparation.*/UsePrivilegeSeparation no/g" /etc/ssh/sshd_config \
&& sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/g' /etc/ssh/ssh_config \
&& echo "root:123456" | chpasswd

RUN mkdir /var/run/sshd

CMD ["/usr/sbin/sshd", "-D"]