FROM centos
COPY mysql.sh /usr/local
COPY mysql-5.6.43.tar.gz /usr/local
COPY bootstrap.sh /etc/bootstrap.sh
RUN yum install  openssh-server openssh-clients unzip python3 python3-setuptools  numactl libaio tar  perl perl-devel perl-Data-Dumper -y \
&& mkdir -p /usr/local/mysql-5.6.43 && tar -zxvf /usr/local/mysql-5.6.43.tar.gz -C /usr/local/mysql-5.6.43 --strip-components 1 \
 && ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' \
 && ssh-keygen -f /root/.ssh/id_rsa -N '' \
 && touch /root/.ssh/authorized_keys \
 && cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys \
 && sed -i 's/#PermitRootLogin  without-password/PermitRootLogin yes/g' /etc/ssh/sshd_config \
 && sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/g' /etc/ssh/ssh_config \
 && echo "root:123456" | chpasswd \
 && rm -rf /etc/my.cnf \
  && mkdir -p /data/mysql \
 && chown -R root:root /usr/local/mysql-5.6.43 \
 && chown root.root /etc/bootstrap.sh \
 && chmod 700 /etc/bootstrap.sh \
 && chmod 700 /usr/local/mysql.sh

COPY mysql_init.sql /usr/local
COPY my.cnf /etc
COPY mysql.server /etc/init.d/mysql
#MYSQL
ENV MYSQL_VERSION 5.6.43
ENV MYSQL_HOME /usr/local/mysql-$MYSQL_VERSION
ENV PATH $PATH:$MYSQL_HOME/bin
CMD ["/usr/bin/mysqld_safe"]
ENTRYPOINT ["/etc/bootstrap.sh"]