version: "2.1"
services:
  master:
    build: .
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
      - 18080
      - 8088
      - 8042
      - 9000
      - 3306
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 50070:50070
      - 9000:9000
      - "40010:22"
      - 18080:18080
      - 8088:8088
      - 8042:8042
      - 8089:8089
      - 3306:3307
    extra_hosts:
      - "master:172.24.0.2"
      - "worker1:172.24.0.3"
      - "worker2:172.24.0.4"
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data

  worker1:
    depends_on:
      - "master"
    build: .
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2048M
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
      - 18080
      - 9000
    ports:
      - 8081:8081
      - "40002:22"
      - 50075:50075
      - 50010:50010
    extra_hosts:
      - "master:172.24.0.2"
      - "worker1:172.24.0.3"
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data