version: "2.1"
services:
  master:
    build: .
    container_name: spark_master
    command:
       bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
      - 18080
      - 8088
      - 8042
      - 9000
      - 9999
      - 10020
      - 50010
      - 9083
      - 10000
      - 2181
      - 16000
      - 16020
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 50070:50070
      - 9000:9000
      - "40010:22"
      - 18080:18080
      - 8088:8088
      - 8042:8042
      - 8089:8089
      - 5066:3306
      - 9999:9999
      - 16030:16030
      - 16010:16010
      - 12000:12000
      - 19888:19888
      - 10002:10002
      - 50010:50010
      - 9083:9083
      - 10000:10000
      - 2181:2181
      - 16000:16000
      - 5005:5005
    extra_hosts:
      - "worker1:172.18.0.3"
      - "worker2:172.18.0.4"
    volumes:
      - ./conf/master:/conf
      - ./tmp:/tmp/data
      - ./data:/data/mysql
  worker1:
    depends_on:
      - "master"
    build: .
    container_name: spark_worker1
    command:
      bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2048M
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
      - 18080
      - 9000
      - 10020
      - 50010
      - 16020
    ports:
      - 8081:8081
      - "40002:22"
      - 50075:50075
      - 50011:50010
      - 16020:16020
    extra_hosts:
      - "master:172.18.0.2"
    volumes:
      - ./conf/master:/conf
      - ./tmp:/tmp/data