FROM centos:7
MAINTAINER zck


#https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tar.xz
COPY bootstrap.sh /etc/bootstrap.sh
ADD Python-3.6.2.tar.xz /usr/local

RUN yum install -y openssl-devel python-setuptools net-tools passwd openssl openssh-server openssh-clients python-virtualenv libaio tar  perl perl-devel perl-Data-Dumper  \
    && yum install -y gcc gcc-c++ libffi-devel python-devel python-pip python-wheel gcc libsasl2-devel penldap-devel bzip2-devel expat-devel gdbm-devel readline-devel sqlite-devel zlib-devel bzip2-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel wget \
    && yum install -y gcc gcc-c++ libffi-devel python-devel python-wheel openssl-devel libsasl2-devel openldap-devel \
    && ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' \
    && ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' \
    && ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key  -N ''  \
    && ssh-keygen -f /root/.ssh/id_rsa -N '' \
    && touch /root/.ssh/authorized_keys \
    && cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys \
    && sed -i "s/UsePAM.*/UsePAM no/g" /etc/ssh/sshd_config \
    && sed -i "s/#UsePrivilegeSeparation.*/UsePrivilegeSeparation no/g" /etc/ssh/sshd_config \
    && sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/g' /etc/ssh/ssh_config \
    && echo "root:123456" | chpasswd \
    && chown root.root /etc/bootstrap.sh \
    && chmod 700 /etc/bootstrap.sh \
    && mkdir /var/run/sshd \
    && cd /usr/local/Python-3.6.2 && ./configure --prefix=/usr/local/python3 \
    && cd /usr/local/Python-3.6.2 && make && make install \
    && ln -s /usr/local/python3/bin/python3 /usr/bin/python3 \
    && ln -s /usr/local/python3/bin/pip3 /usr/bin/pip3 \
    && pip3 install --upgrade pip \
    && pip3 install virtualenv

#pip3 install --upgrade setuptools pip -i https://pypi.douban.com/simple
#mkdir -p /tmp/py3_env
#virtualenv -p /usr/local/python3/bin/python3 /tmp/py3_env/
#/usr/local/python3/bin/virtualenv venv
#cd venv
#source bin/activate

#source /tmp/py3_env/bin/activate
#deactivate
#pip3 install pandas==0.23.4
#pip3 install SQLAlchemy==1.2.18
#pip3 install superset -i https://pypi.douban.com/simple
#pip3 install kylinpy
#export LANG=en_US.utf8

#运行 fabmanager create-admin --app superset 创建admin账户并设置相应信息
#运行 superset db upgrade 初始化数据库
#运行 superset load_examples 初始化数据
#运行 superset init 初始化SuperSet
#运行 superset runserver & 后台运行SuperSet
#superset runserver -d
CMD ["/usr/sbin/init"]
ENTRYPOINT ["/etc/bootstrap.sh"]

