version: "2.1"
services:
  master:
    build: .
    container_name: spark_master
    hostname: master
    privileged: true
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
      - 18080
      - 8088
      - 8042
      - 9000
      - 9999
      - 10020
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 50070:50070
      - 9000:9000
      - "40010:22"
      - 18080:18080
      - 8088:8088
      - 8042:8042
      - 8089:8089
      - 5066:3306
      - 9999:9999
      - 16030:16030
      - 16010:16010
      - 12000:12000
      - 19888:19888
    extra_hosts:
      - "worker1:172.24.0.3"
      - "worker2:172.24.0.4"
    volumes:
      - ./tmp:/tmp/data
      - ./data:/data/mysql
  worker1:
    depends_on:
      - "master"
    build: .
    container_name: spark_worker1
    privileged: true
    hostname: worker1
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
      - 18080
      - 9000
      - 10020
    ports:
      - 8081:8081
      - "40002:22"
      - 50075:50075
      - 50010:50010
    extra_hosts:
      - "master:172.24.0.2"
    volumes:
      - ./tmp:/tmp/data
      - ./data:/data/mysql